import type { TranslationMap } from './types';

export const trabaja: TranslationMap = {
  trabaja_une_equipo: { es: 'Únete a Nuestro Equipo', en: 'Join Our Team', fr: 'Rejoignez Notre Équipe', de: 'Werden Sie Teil unseres Teams', pt: 'Junte-se à Nossa Equipe' },
  trabaja_trabaja_nosotros: { es: 'Trabaja con Nosotros', en: 'Work with Us', fr: 'Travaillez avec Nous', de: 'Arbeiten Sie mit uns', pt: 'Trabalhe Conosco' },
  trabaja_descripcion: { es: 'En Huarmy Coffee valoramos el talento, la pasión por la gastronomía tradicional y el servicio al cliente de excelencia. Si quieres crecer profesionalmente con nosotros, déjanos tus datos.', en: 'At Huarmy Coffee we value talent, a passion for traditional gastronomy and excellent customer service. If you want to grow professionally with us, leave us your details.', fr: 'Chez Huarmy Coffee, nous valorisons le talent, la passion pour la gastronomie traditionnelle et un service client d\'excellence. Si vous souhaitez évoluer professionnellement avec nous, laissez-nous vos coordonnées.', de: 'Bei Huarmy Coffee schätzen wir Talent, die Leidenschaft für traditionelle Gastronomie und exzellenten Kundenservice. Wenn Sie beruflich mit uns wachsen möchten, hinterlassen Sie uns Ihre Daten.', pt: 'Na Huarmy Coffee valorizamos o talento, a paixão pela gastronomia tradicional e o atendimento ao cliente de excelência. Se você quer crescer profissionalmente conosco, deixe seus dados.' },
  trabaja_oportunidades: { es: 'Oportunidades de Crecimiento', en: 'Growth Opportunities', fr: 'Opportunités de Croissance', de: 'Wachstumsmöglichkeiten', pt: 'Oportunidades de Crescimento' },
  trabaja_capacitacion: { es: 'Capacitación constante en barismo, servicio y cocina típica.', en: 'Ongoing training in barista skills, service and traditional cooking.', fr: 'Formation continue en barista, service et cuisine typique.', de: 'Ständige Schulungen in Barista-Kunst, Service und traditioneller Küche.', pt: 'Capacitação constante em barismo, serviço e culinária típica.' },
  trabaja_exito_titulo: { es: '¡Postulación Enviada con Éxito!', en: 'Application Submitted Successfully!', fr: 'Candidature Envoyée avec Succès !', de: 'Bewerbung erfolgreich übermittelt!', pt: 'Inscrição Enviada com Sucesso!' },
  trabaja_exito_descripcion: { es: 'Hemos recibido tus datos y los revisaremos para futuras vacantes. Gracias por tu interés.', en: 'We have received your details and will review them for future vacancies. Thank you for your interest.', fr: 'Nous avons bien reçu vos coordonnées et les examinerons pour de futures offres. Merci pour votre intérêt.', de: 'Wir haben Ihre Daten erhalten und werden sie für künftige Stellen prüfen. Vielen Dank für Ihr Interesse.', pt: 'Recebemos seus dados e os analisaremos para futuras vagas. Obrigado pelo seu interesse.' },
  trabaja_enviar_otra: { es: 'Enviar otra postulación', en: 'Submit another application', fr: 'Envoyer une autre candidature', de: 'Eine weitere Bewerbung senden', pt: 'Enviar outra inscrição' },
  trabaja_formulario_titulo: { es: 'Formulario de Postulación', en: 'Application Form', fr: 'Formulaire de Candidature', de: 'Bewerbungsformular', pt: 'Formulário de Inscrição' },
  trabaja_label_nombre: { es: 'Nombre Completo', en: 'Full Name', fr: 'Nom Complet', de: 'Vollständiger Name', pt: 'Nome Completo' },
  trabaja_placeholder_nombre: { es: 'Tu nombre', en: 'Your name', fr: 'Votre nom', de: 'Ihr Name', pt: 'Seu nome' },
  trabaja_label_correo: { es: 'Correo Electrónico', en: 'Email Address', fr: 'Adresse E-mail', de: 'E-Mail-Adresse', pt: 'E-mail' },
  trabaja_placeholder_correo: { es: 'ejemplo@correo.com', en: 'example@email.com', fr: 'exemple@email.fr', de: 'beispiel@email.de', pt: 'exemplo@email.com' },
  trabaja_label_telefono: { es: 'Teléfono de Contacto', en: 'Contact Phone', fr: 'Téléphone de Contact', de: 'Kontakttelefon', pt: 'Telefone de Contato' },
  trabaja_label_mensaje: { es: 'Mensaje / Carta de Presentación', en: 'Message / Cover Letter', fr: 'Message / Lettre de Motivation', de: 'Nachricht / Bewerbungsschreiben', pt: 'Mensagem / Carta de Apresentação' },
  trabaja_placeholder_mensaje: { es: 'Cuéntanos un poco sobre tu experiencia laboral y por qué quieres unirte...', en: 'Tell us a bit about your work experience and why you want to join...', fr: 'Parlez-nous un peu de votre expérience professionnelle et de pourquoi vous souhaitez nous rejoindre...', de: 'Erzählen Sie uns etwas über Ihre Berufserfahrung und warum Sie zu uns kommen möchten...', pt: 'Conte-nos um pouco sobre sua experiência profissional e por que você quer se juntar a nós...' },
  trabaja_enviando: { es: 'Enviando...', en: 'Sending...', fr: 'Envoi en cours...', de: 'Senden...', pt: 'Enviando...' },
  trabaja_enviar_postulacion: { es: 'Enviar Postulación', en: 'Submit Application', fr: 'Envoyer la Candidature', de: 'Bewerbung senden', pt: 'Enviar Inscrição' },
  trabaja_error_envio: { es: 'Error al enviar la postulación.', en: 'Error sending your application.', fr: 'Erreur lors de l\'envoi de la candidature.', de: 'Fehler beim Senden der Bewerbung.', pt: 'Erro ao enviar a inscrição.' },
  trabaja_error_conexion: { es: 'Error de conexión con el servidor. Inténtalo más tarde.', en: 'Connection error with the server. Try again later.', fr: 'Erreur de connexion au serveur. Réessayez plus tard.', de: 'Verbindungsfehler mit dem Server. Versuchen Sie es später erneut.', pt: 'Erro de conexão com o servidor. Tente novamente mais tarde.' },
};
